name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    env:
      USING_COVERAGE: "3.11"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up OS dependencies
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable libmagic
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install --cask google-chrome
            brew install libmagic
          fi
        shell: bash

      - name: Install python dependencies
        run: python -m pip install tox-gh-actions poetry

      - name: Run tox
        run: poetry run tox

  package:
    name: Build package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Build package
        run: poetry build

      - name: Show result
        run: ls -l dist

      - name: Install package
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libmagic
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install libmagic
          fi
          python -m pip install .

      - name: Import package
        run: python -c "import skipy"
